#!/bin/bash

function changeOption() {
  baseOption=$(grep "$1" $2);
  if [ "$2" = "/tmp/client.conf" ]; then delimiter=" "; else delimiter="="; fi
  option=$(echo $baseOption | cut -d "$delimiter" -f 1);
  sed -i "s/$baseOption/${option}=${3}/" $2;
}

function err_InvalidValue() {
  echo "You need to put valid option value";
}

function err_InvalidOrAbsValue() {
  echo "You need to put option value";
}

function send() {
  scp $1 pi@mrtr.local:$2;
}

function copy() {
  ssh pi@mrtr.local "sudo cp $1 $2";
}

function fetch() {
  scp pi@mrtr.local:$1 $2;
}

function help() {
  echo "mrtr - script for config and controling MRTR device";
  echo "morketsmerke.net @ 2023";
  echo;
  echo "interface - module for configure and control ethernet and wireless interfaces";
  echo "password  - set password for MRTR pi user";
  echo "service   - start and stop dnsmasq or hostapd services";
  echo "ap        - configure a broadcasted wireless network";
  echo "dhcp      - configure a dhcp service. More info DHCP section.";
  echo "openvpn   - configure a openvpn (client role) service";
  echo "wlan      - establish connection with wireless LAN network";
  echo;
  echo "INTERFACE:";
  echo "  $ mrtr interface <ethX/wlanX> <IP address/dhcp>";
  echo "  The interface subcommand settings IP address and put appropiate";
  echo "  entry to /etc/dhcpcd.conf file setting given IP address as static";
  echo "  configuration for this interface";
  echo "  #FIX_ME! Setting dhcp, should delete interface entry from file";
  echo;
  echo "PASSWORD:";
  echo "  $ mrtr password <password_for_pi_user>";
  echo "  Installation script will check that pi user is already in this";
  echo "  system or not, if its not then this user will be created with simple";
  echo "  password. So this subcommand let you change default pi user password";
  echo;
  echo "SERVICE:";
  echo "  $ mrtr service <hostapd/dnsmasq/openvpn> <on/off>";
  echo "  This subcommand it's a pretty alias for systemctl start and stop";
  echo "  actions. For now supports only 3 services and 2 actions.";
  echo;
  echo "AP:";
  echo "  $ mrtr ap";
  echo "    <ssid> <wlan_network_name>";
  echo "    <mode> <a|b|g> (Warning! Mode 'a' for RPi 3B+ only.)";
  echo "    <channel> <1-13>";
  echo "    <hide_ssid> <0|1>";
  echo "    <psk> <wlan_password>";
  echo;
  echo "DHCP:";
  echo "  $ mrtr dhcp";
  echo "    <range> <start_ip-end_ip>";
  echo "    <gateway> <gateway_ip_address>";
  echo "    <dns> <primary_dns_ip,secondary_dns_ip>";
  echo "    <interface> <ethX/wlanX>";
  echo;
  echo "OPENVPN:";
  echo "  $ mrtr openvpn";
  echo "    <server> <openvpn_remote_server_ip>";
  echo "    <cacert> <ca_cert_path>";
  echo "    <cert> <cert_path>";
  echo "    <key> <key_path>";
  echo "  The paths should be from local system, not remote. Pointed files";
  echo "  will be uploaded to MRTR device and copied to the appropiate place";
  echo;
  echo "NETSUM:";
  echo "  $ mrtr netsum";
  echo "  Run a netsum script (print a huge information about network";
  echo "  configuration)";
  echo;
  echo "WLAN:";
  echo "  $ mrtr wlan";
  echo "    <scan>";
  echo "    <connect> <essid> [psk]";
  echo "  If you are trying connect to previous networks, ESSID is everything";
  echo "  that you need to put";
}
regexForIP='[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'

if ping -q -c 1 mrtr.local > /dev/null 2>&1; then
  if [ "$1" ]; then
    case $1 in
      'interface') if [ "$2" ] && echo $2 | grep -Eq '(eth[0-9]*|wlan[0-9]*)'; then
                      if [ "$3" ] && echo $3 | grep -q '[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\/[0-9]*'; then
                        ssh pi@mrtr.local "sudo ip address replace $3 dev $2";
                        if echo $2 | grep 'wlan[0-9]*'; then
                          msg="interface $2\n\tstatic ip_address $3\n\tnohook wpa_supplicant";
                        else
                          msg="interface $2\n\tstatic ip_address $3";
                        fi
                          ssh pi@mrtr.local "echo -e \"$msg\" | sudo tee -a /etc/dhcpcd.conf";
                      elif [ "$3" ] && [ "$3" = "dhcp" ]; then
                        ssh pi@mrtr.local "sudo ip address flush dev $2";
                        ssh pi@mrtr.local "sudo dhclient $2 -v";
                        startStaticEntry=$(ssh pi@mrtr.local "grep -n \"^interface $2\" /etc/dhcpcd.conf | cut -d \":\" -f 1");
                        if echo $2 | grep -q "wlan[0-9]*"; then
                          endStaticEntry=$((startStaticEntry + 2));
                        else
                          endStaticEntry=$((startStaticEntry + 1));
                        fi
                        ssh pi@mrtr.local "sudo sed -i \"${startStaticEntry},${endStaticEntry}d\" /etc/dhcpcd.conf";
                      else
                        echo "Given IP address isn't valid for CIDR notation";
                      fi
                   else
                      echo "Given interface name isn't valid for Rasperry Pi OS interface naming";
                   fi;;
      'password') if [ "$2" ]; then
                      ssh pi@mrtr.local "echo\"pi:$2\" | chpasswd";
                  else
                    err_InvalidOrAbsValue;
                  fi;;
      'service') if [ "$2" ] && ([ $2 = "dnsmasq" ] || [ $2 = "hostapd" ] || [ $2 = "openvpn" ]); then
                  if [ "$3" ] && ([ $3 = "on" ] || [ $3 = "off" ]); then
                      if [ $3 = "on" ]; then action="start"; else action="stop"; fi
                      if [ $2 = "hostapd" ] && [ $3 = "on" ]; then
                        ssh pi@mrtr.local "sudo systemctl unmask hostpad.service";
                      fi 
                      ssh pi@mrtr.local "sudo systemctl $action ${2}.service";
                  fi
                 fi;;
      'ap') ssh pi@mrtr.local "if [ -f /etc/hostapd/hostapd.conf ]; then exit 0; else exit 1; fi";
                  if [ $? -eq 0 ]; then
                    #scp pi@mrtr.local:/etc/hostapd/hostpad.conf /tmp/hostapd.conf;
                    fetch /etc/hostpad/hostapd.conf /tmp/hostapd.conf;
                  else
                    cat > /tmp/hostapd.conf <<EOF
country_code=PL
interface=wlan0
ssid=NameOfNetwork
hw_mode=g
channel=7
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=AardvarkBadgerHedgehog
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
EOF
                  fi
                  if [ "$2" ]; then
                    case $2 in
                      'ssid') if [ "$3" ]; then
                                changeOption '^ssid=' /tmp/hostapd.conf $3;
                              else
                                eerr_InvalidOrAbsValue;
                              fi;;
                      'mode') if [ "$3" ] && echo $3 | grep -Eq 'a|b|g'; then
                                changeOption '^hw_mode=' /tmp/hostpad.conf $3;
                              else
                                eerr_InvalidValue;
                              fi;;
                      'channel') if [ "$3" ] && echo $3 | grep -q '[0-9]*'; then
                                  changeOption '^channel=' /tmp/hostapd.conf $3;
                                 else
                                  eerr_InvalidValue;
                                 fi;;
                      'hide_ssid') if [ "$3" ] && echo $3 | grep -Eq '0|1'; then
                                    changeOption '^ignore_broadcast_ssid=' /tmp/hostapd.conf $3;                                   else
                                    err_InvalidValue;
                                   fi;;
                      'psk') if [ "$3" ]; then
                              changeOption '^wpa_passphrase=' /tmp/hostapd.conf $3;
                             else
                              err_InvalidOrAbsValue;
                             fi;;
                    esac
                    #scp /tmp/hostapd.conf pi@mrtr.local:/home/pi;
                    send /tmp/hostapd.conf /home/pi;
                    #ssh pi@mrtr.local "sudo cp ~/hostapd.conf /etc/hostapd";
                    copy /home/pi/hostapd.conf /etc/hostapd.conf
                  else
                    help;
                    exit 1;
                  fi;;
      'dhcp')  ssh pi@mrtr.local "if [ -f /etc/dnsmasq.conf ]; then exit 0; else exit 1; fi";
                  if [ $? -eq 0 ]; then
                    #scp pi@mrtr.local:/etc/dnsmasq.conf /tmp/dnsmasq.conf;
                    fetch /etc/dnsmasq.conf /tmp/dnsmasq.conf
                  else
                    cat > /tmp/dnsmasq.conf <<EOF
inteface=eth0
dhcp-range=192.168.4.2,192.168.4.20,255.255.255.0,12h
dhcp-option=3,192.168.4.1
dhcp-option=6,192.168.4.1
EOF
                  fi
                  if [ "$2" ]; then
                    case $2 in
                      'range') if [ "$3" ] && echo $3 | grep -Eq "${regexForIP}-${regexForIP}"; then
                                ipRange=$(echo $3 | sed 's/-/,/');
                                changeOption '^dhcp-range' /tmp/dnsmasq.conf "${ipRange},255.255.255.0,12h";
                               else
                                err_InvalidValue;
                               fi;;
                      'gateway') if [ "$3" ] && echo $3 | grep -Eq "${regexForIP}"; then
                                  changeOption '^dhcp-option=3' /tmp/dnsmasq.conf "3,${3}";
                                 else
                                  err_InvalidValue;
                                 fi;;
                      'dns') if [ "$3" ] && echo $3 | grep -Eq "${regexForIP}"; then
                              changeOption '^dhcp-option=6' /tmp/dnsmasq.conf "6,${3}";
                             else
                              err_InvalidValue;
                             fi;;
                      'interface') if [ "$3" ] && echo $3 | grep -Eq "(eth[0-9]* | wlan[0-9])"; then
                                    changeOption '^interface' /tmp/dnsmasq.conf $3;
                                   else
                                    err_InvalidValue;
                                   fi;;
                    esac
                    #scp /tmp/dnsmasq.conf pi@mrtr.local:/home/pi;
                    send /tmp/dnsmasq.conf /home/pi;
                    #ssh pi@mrtr.local "sudo cp ~/dnsmasq.conf /etc";
                    copy /home/pi/dnsmasq.conf /etc;
                  else
                    help;
                    exit 1;
                  fi;;
      'openvpn') ssh pi@mrtr.local "if [ -f /etc/openvpn/client/client.conf ]; then exit 0 else exit 1; fi"
                 if [ $? -eq 0 ]; then
                  #scp pi@mrtr.local:/etc/openvpn/client/client.conf /tmp;
                  fetch /etc/openvpn/client/client.conf /tmp;
                 else
                  cat > /tmp/client.conf <<EOF
dev tun
client
remote 54.37.235.189
proto udp
port 17003
nobind
ca cacert.pem
cert immudex_cert.pem
key immudex_key.pem_nopass
verb 3
EOF
                  fi
                  if [ "$2" ]; then
                    case $2 in
                      'server') if [ "$3" ] && echo $3 | grep -Eq "${regexForIP}"; then
                                 changeOption '^remote' /tmp/client.conf $3;
                                else
                                 err_InvalidValue;
                                fi;;
                      'cacert') if [ "$3" ] && echo $3 | grep -Eq "[a-z]*\/[a-z]*\.pem"; then
                                  filename=$(basename $3);
                                  changeOption '^cacert' /tmp/client.conf $filename;
                                  send $3 /home/pi;
                                  copy /home/pi/$filename /etc/openvpn/client/$filename;
                                else
                                  err_InvalidValue;
                                fi;;
                      'cert') if [ "$3" ] && echo $3 | grep -Eq "[a-z]*\/[a-z]*\.pem"; then
                                filename=$(basename $3);
                                changeOption '^cert' /tmp/client.conf $filename;
                                send $3 /home/pi;
                                copy /home/pi/$filename /etc/openvpn/client/$filename;
                              else
                                err_InvalidValue;
                              fi;;
                      'key') if [ "$3" ] && echo $3 | grep -Eq "[a-z]*\/[a-z]*\.pem"; then
                                filename=$(basename $3);
                                changeOption '^key' /tmp/client.conf $filename;
                                send $3 /home/pi;
                                copy /home/pi/$filename /etc/openvpn/client/$filename;
                              else
                                err_InvalidValue;
                              fi;;
                    esac
                  else
                    help;
                    exit 1;
                  fi;;
      'netsum') if [ -x /usr/local/bin/netsum ]; then 
                  ssh pi@mrtr.local "sudo netsum -o stdout";
                else echo "Netsum tool not found";
                fi;;
      'wlan') ssh pi@mrtr.local "if [ -x /usr/local/bin/wlanconn ]; then exit 0; else exit 1; fi"; 
              if [ $? -eq 0 ]; then
                if [ "$2" ]; then
                  case $2 in
                    'scan') ssh pi@mrtr.local "wlanconn list";;
                    'connect') if [ "$3" ]; then
                                if [ "$4" ]; then
                                  ssh pi@mrtr.local "wlanconn $3 $4";
                                else
                                  ssh pi@mrtr.local "wlanconn $3";
                                fi
                               else
                                help;
                                exit 1;
                               fi; 
                  esac
                else
                  help;
                  exit 1;  
                fi
              else
                echo "Wlanconn tool not found";
              fi;;  
    esac
  else
    help;
    exit 1;
  fi
else
  echo "MRTR device isn't available now.";
fi
if [ "$1" ] && [ "$1" = "help" ]; then
    help;
    exit 0;
fi
